# github action that checks code with Rector
name: Rector

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  rector:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - uses: ramsey/composer-install@v3

      - name: Run Rector
        run: vendor/bin/rector process --ansi

      - name: Commit Rector changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[rector] Rector fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'
